import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:http/http.dart';

import 'model_class.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<Autogenerated> listData = [];

  @override
  void initState() {
    getData();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.purple,
          title: const Text('Http_API'),
        ),
        body: ListView.builder(
            itemCount: listData.length,
            itemBuilder: (BuildContext context, int index) {
              return Container(
                child: Card(
                  //color: Color(colorList[index]),
                  child: Column(
                    children: [
                      Text(listData[index].userId!.toString()),
                      Text(listData[index].id!.toString()),
                      Text(listData[index].title!.toString()),
                      Text(listData[index].completed!.toString()),
                    ],
                  ),
                ),
              );
            }),
      ),
    );
  }
// [[dsts]]
  getData() async {
    Uri url = Uri.parse('https://jsonplaceholder.typicode.com/todos');
    http.Response r1 = await get(url);
    print(r1.bodyBytes);
    switch (r1.statusCode) {
      case 200:
        List resdata = jsonDecode(r1.body);
        listData = resdata.map((e) => Autogenerated.fromJson(e)).toList();
        debugPrint(listData.toString());
        setState(() {});
      // Autogenerated.fromJson(resdata) as List<Autogenerated>;

    }
  }
}
